import { it, expect, vi, afterEach } from "vitest";
import { render, screen, fireEvent, waitFor, cleanup, within } from '@testing-library/react';
import { DiagnosticsPanel } from './DiagnosticsPanel';
import { run, runId, technical, response, at, mockApi } from './fixtures.test-support';
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
it('operator diagnoses stalled Power Automate dependency through list/detail/timeline', async () => {
    const fetcher = mockApi();
    render(<DiagnosticsPanel />);
    await screen.findByRole('button', { name: `Open run ${runId}` });
    expect(screen.getByText('Showing 1 matching runs on this page. Snapshot:', { exact: false })).toBeInTheDocument();
    fireEvent.click(screen.getByRole('button', { name: `Open run ${runId}` }));
    await screen.findByText('Deployment & trace correlation');
    expect(screen.getByText(technical.trace_id)).toBeInTheDocument();
    await screen.findByText(/Earlier diagnostic events were truncated/);
    expect(screen.getAllByText(/Power Automate gateway/).length).toBeGreaterThan(0);
    expect(screen.getByText('Operational timeline')).toBeInTheDocument();
    expect(fetcher.mock.calls.some(c => String(c[0]).endsWith('/timeline?limit=25'))).toBe(true);
});
it('preserves RUNNING + STALE without synthesizing failure or timeout', async () => {
    vi.spyOn(globalThis, 'fetch').mockResolvedValue(response({ items: [run({ status: 'RUNNING', classification: 'STALE', error_code: undefined })], as_of: at }));
    render(<DiagnosticsPanel />);
    await screen.findByText('RUNNING');
    expect(screen.getByText('· STALE')).toBeInTheDocument();
    expect(within(screen.getByRole('table')).queryByText('FAILED')).not.toBeInTheDocument();
    expect(within(screen.getByRole('table')).queryByText('TIMEOUT')).not.toBeInTheDocument();
});
it.each([401, 403])('clears authorized technical detail immediately on refresh %i', async (status) => {
    const fetcher = mockApi();
    render(<DiagnosticsPanel />);
    fireEvent.change(screen.getByLabelText('Exact run ID'), { target: { value: runId } });
    fireEvent.click(screen.getByText('Find run'));
    await screen.findByText(technical.trace_id);
    fetcher.mockResolvedValue(response({ raw: 'SECRET' }, status));
    fireEvent.click(screen.getAllByText('Refresh')[0]);
    await waitFor(() => expect(screen.queryByText(technical.trace_id)).not.toBeInTheDocument());
    expect(screen.queryByText('Deployment & trace correlation')).not.toBeInTheDocument();
    expect(screen.getByRole('alert')).toHaveTextContent(status === 401 ? 'current authenticated context' : 'not permitted');
});
it('uses pagination and filters, exact lookup and recent empty state', async () => {
    const fetcher = vi.spyOn(globalThis, 'fetch').mockResolvedValue(response({ items: [run()], as_of: at, next_cursor: 'YWJj==' }));
    render(<DiagnosticsPanel />);
    await screen.findByRole('button', { name: `Open run ${runId}` });
    fireEvent.click(screen.getByText('Next page'));
    await waitFor(() => expect(fetcher.mock.calls.some(c => String(c[0]).includes('cursor=YWJj%3D%3D'))).toBe(true));
    fireEvent.change(screen.getByLabelText('Status filter'), { target: { value: 'FAILED' } });
    await waitFor(() => expect(String(fetcher.mock.calls.at(-1)?.[0])).toContain('status=FAILED'));
    expect(String(fetcher.mock.calls.at(-1)?.[0])).not.toContain('cursor=');
    fetcher.mockResolvedValue(response({ items: [], as_of: at }));
    fireEvent.click(screen.getByText('Recent runs'));
    await screen.findByText('No recent runs were returned for this filter.');
    fireEvent.click(screen.getByText('Find run'));
    expect(screen.getByRole('alert')).toHaveTextContent('canonical run UUID');
});
it.each(['FAILED', 'TIMEOUT', 'CANCELLED', 'COMPLETED', 'STALLED'] as const)('shows backend canonical %s', async (status) => { vi.spyOn(globalThis, 'fetch').mockResolvedValue(response({ items: [run({ status })], as_of: at })); render(<DiagnosticsPanel />); expect(await screen.findByText(status)).toBeInTheDocument(); });
it('timeline failure is isolated from summary and empty events are meaningful', async () => { const fetcher = mockApi({ empty: true }); render(<DiagnosticsPanel />); fireEvent.change(screen.getByLabelText('Exact run ID'), { target: { value: runId } }); fireEvent.click(screen.getByText('Find run')); await screen.findByText(technical.trace_id); await screen.findByText('No diagnostic events available.'); fetcher.mockResolvedValue(response({}, 503)); fireEvent.click(screen.getAllByText('Refresh')[1]); await screen.findByRole('alert'); expect(screen.getByText(technical.trace_id)).toBeInTheDocument(); });
it('safely isolates unsupported schema and malformed responses', async () => {
    const fetcher = vi.spyOn(globalThis, 'fetch').mockImplementation(async () => response({ items: [{ ...run(), technical: { ...technical, telemetry_schema_version: 2 } }], as_of: at }));
    render(<DiagnosticsPanel />);
    await screen.findByText('This diagnostics schema is not supported by this UI version.');
    expect(screen.queryByRole('table')).not.toBeInTheDocument();
    fetcher.mockImplementation(async () => response({ items: 'bad' }));
    fireEvent.click(screen.getByText('Refresh'));
    await screen.findByText('The diagnostic response could not be read safely.');
});
it('applies environment/time filters only on submit with bounded ranges', async () => {
    const fetcher = mockApi();
    render(<DiagnosticsPanel />);
    await screen.findByRole('table');
    fireEvent.click(screen.getByText('Environment & time filters'));
    const before = fetcher.mock.calls.length;
    fireEvent.change(screen.getByLabelText('Environment filter'), { target: { value: 'development' } });
    fireEvent.change(screen.getByLabelText('From time filter'), { target: { value: '2026-10-08T10:00' } });
    fireEvent.change(screen.getByLabelText('Until time filter'), { target: { value: '2026-10-08T12:00' } });
    expect(fetcher).toHaveBeenCalledTimes(before);
    fireEvent.click(screen.getByText('Apply filters'));
    await waitFor(() => expect(String(fetcher.mock.calls.at(-1)?.[0])).toContain('environment=development'));
    expect(String(fetcher.mock.calls.at(-1)?.[0])).toContain('since=');
    fireEvent.change(screen.getByLabelText('From time filter'), { target: { value: '2025-01-01T10:00' } });
    fireEvent.click(screen.getByText('Apply filters'));
    expect(screen.getByRole('alert')).toHaveTextContent('at most 90 days');
});
it('preserves list filters and recent mode while drilling down and returning', async () => {
    const api = mockApi();
    render(<DiagnosticsPanel />);
    await screen.findByRole('table');
    fireEvent.click(screen.getByText('Recent runs'));
    fireEvent.change(screen.getByLabelText('Status filter'), { target: { value: 'STALLED' } });
    await screen.findByRole('table');
    fireEvent.click(screen.getByRole('button', { name: `Open run ${runId}` }));
    await screen.findByText(technical.trace_id);
    fireEvent.click(screen.getByText('Back to runs'));
    await screen.findByRole('table');
    expect(screen.getByLabelText('Status filter')).toHaveValue('STALLED');
    expect(String(api.mock.calls.at(-1)?.[0])).toContain('/runs?');
    expect(String(api.mock.calls.at(-1)?.[0])).toContain('status=STALLED');
});
