import { it, expect, vi, afterEach } from "vitest";
import { render, screen, cleanup, fireEvent } from '@testing-library/react';
import { ReliabilityPanel } from './ReliabilityPanel';
import { DataRetentionPanel } from './DataRetentionPanel';
import { FinOpsPanel } from './FinOpsPanel';
import { IntegrationsPanel } from './IntegrationsPanel';
import { AccessPanel } from './AccessPanel';
import { OverviewPanel } from './OverviewPanel';
import { mockApi, response, run, at, technical } from './fixtures.test-support';
afterEach(() => { cleanup(); vi.restoreAllMocks(); });
it('renders effective read-only provisional reliability and retention', async () => { mockApi(); const view = render(<ReliabilityPanel />); await screen.findByText('180s'); expect(screen.getByText(/Provisional defaults/)).toHaveTextContent('not production-approved SLOs'); expect(screen.queryByRole('textbox')).not.toBeInTheDocument(); expect(screen.queryByText('Save')).not.toBeInTheDocument(); view.unmount(); render(<DataRetentionPanel />); await screen.findByText('24h'); expect(screen.getByText('30d')).toBeInTheDocument(); expect(screen.getByText('90d')).toBeInTheDocument(); expect(screen.getByText(/128 significant events/)).toBeInTheDocument(); });
it('future panels have no accounting requests, charts, percentages or invented costs', () => { const fetcher = vi.spyOn(globalThis, 'fetch'); render(<FinOpsPanel />); expect(screen.getByText('Accounting starts in M10.')).toBeInTheDocument(); expect(document.body.textContent).not.toMatch(/0%|€|\$[0-9]/); expect(fetcher).not.toHaveBeenCalled(); });
it('reports actual integration boundaries and distinguishes unknown delivery', async () => { mockApi(); render(<IntegrationsPanel />); await screen.findByText('unknown', { exact: false }); expect(screen.getByText('Teams gateway — Power Automate')).toBeInTheDocument(); expect(screen.getByText('Direct Microsoft Graph telemetry is not available.')).toBeInTheDocument(); expect(screen.getByText(/Cloud SQL infrastructure health is not reported/)).toBeInTheDocument(); });
it('shows independent Access outcomes, without inferred identity or roles', async () => { mockApi({ configDenied: true }); render(<AccessPanel />); await screen.findByText(/operational health request was permitted/); await screen.findByRole('alert'); expect(screen.getByText(/not exposed by the current API/)).toBeInTheDocument(); expect(screen.queryByRole('combobox')).not.toBeInTheDocument(); });
it('health failure does not break independent overview lists', async () => { mockApi({ healthFailed: true }); render(<OverviewPanel />); await screen.findByRole('alert'); expect((await screen.findAllByRole('button', { name: /Open run/ })).length).toBe(2); expect(screen.getAllByText(/Showing 1 matching runs on this page/).length).toBe(2); });
it('privacy sentinels in unknown extras/enums are absent from DOM/storage/console', async () => {
    const sentinel = 'SECRET_PROMPT_TEAMS_COMMAND_SQL_WEBHOOK_TOKEN_KNOWLEDGE';
    const debug = vi.spyOn(console, 'debug');
    const log = vi.spyOn(console, 'log');
    const store = vi.spyOn(Storage.prototype, 'setItem');
    vi.spyOn(globalThis, 'fetch').mockImplementation(async () => response({ items: [{ ...run(), prompt: sentinel, teams: sentinel, command: sentinel, sql: sentinel, secret_url: sentinel, token: sentinel, knowledge: sentinel, current_tool: sentinel, error_code: sentinel, technical: { ...technical, body: sentinel } }], as_of: at }));
    render(<OverviewPanel />);
    const buttons = await screen.findAllByRole('button', { name: /Open run/ });
    expect(document.body.textContent).not.toContain(sentinel);
    expect(store).not.toHaveBeenCalled();
    expect(debug).not.toHaveBeenCalled();
    expect(log).not.toHaveBeenCalled();
    fireEvent.click(buttons[0]);
});
