"""Deterministic evidence validation for incident_manager.

"Do not trust arbitrary message IDs generated by the LLM" -- this module
is the enforcement, not just a prompt instruction. `validate_evidence` is
the pure, directly-testable rule: an `evidence` entry survives only if its
`message_id` is in the set of message ids actually retrieved (or actually
present inside a retrieved message's `message_references`) this turn --
see `backend/tools/teams/get_messages.py`'s `KNOWN_MESSAGE_IDS_STATE_KEY`,
which `teams_get_messages` populates as it runs.

`strip_unverified_evidence` wires that rule into the ADK runtime: it
inspects incident_manager's own final structured response (already
produced and validated against `IncidentManagerResponse` by the
model/ADK), re-checks every `evidence[].message_id` against the session's
actual `known_message_ids`, and -- only if something needed to be removed
-- returns a corrected `Content` that ADK treats as this turn's real
final output, which `AgentTool` (docs/AGENT_CONTRACT.md #4) then returns
to team_manager instead of the unverified one. This mirrors the same
philosophy already used for the write-tool approval gate elsewhere in
this codebase: prompt instructions alone are not a sufficient control,
so the guarantee is enforced in deterministic code that runs regardless
of what the model was told or "believed" was true.

This module does NOT attempt semantic validation of whether a message
truly supports a claim -- only that the cited provenance is real,
retrieved Teams data (per the task's explicit instruction not to
second-guess relevance, only existence).

THIRD PRE-4H CORRECTION PASS: `agent.py`'s own `after_agent_callback` is
now `enforce_incident_manager_response_integrity` (below), not
`strip_unverified_evidence` directly -- it runs
`provenance_compliance.enforce_governed_knowledge_selection` FIRST (the
new "SEARCH RESULT != EVIDENCE USED" enforcement -- see that module's own
docstring), then applies this module's existing, UNCHANGED Teams
evidence-stripping check to whatever text is final afterward, so a
corrected combined (Teams + governed knowledge) answer is still subject
to the SAME Teams-evidence validation every other incident_manager turn
already gets. `strip_unverified_evidence` itself is untouched -- still
directly tested, still used unmodified by every OTHER incident_manager
variant that inherits `after_agent_callback` without overriding it and
never sets `requires_governed_knowledge=true` in the first place
(`_CONTINUATION_INCIDENT_MANAGER`/`_SYNTHESIS_ONLY_INCIDENT_MANAGER`,
read_continuation_execution.py).

DEF-0024 CORRECTIVE PASS (Alarm Procedure Granularity & Procedure-
Scoped Grounding): `enforce_procedure_scoped_command_grounding` closes a
real live defect -- a command reproduced verbatim from Approved,
selected governed knowledge could still belong to a DIFFERENT procedure
than the one the current turn is actually about, if that sibling
procedure happened to be coarsely packaged into the same selected
`KnowledgeSection`. Wired into `_capture_and_render_troubleshooting_
guidance` (same "deterministic code, not prompt-only self-restraint"
philosophy as the rest of this module): a command/step-command is
trusted ONLY if it is a literal substring of THIS run's own genuinely
selected evidence sections' real content -- identity/content-based,
never a semantic "is this the right procedure" judgment.

DEF-0027 CORRECTIVE PASS (Active-Procedure Command Grounding &
Conditional Command Handling): DEF-0024's own rule -- "if more than one
section is selected this turn, a command must be grounded in ALL of
them" -- was correct as a fail-closed default but too broad for a real,
live-observed shape: a genuinely ACTIVE procedure (e.g. "HW Partial
Fault", explicitly named by the current question) selected ALONGSIDE a
merely SUPPORTING sibling section (e.g. "HW Fault") whose own real
command the active procedure never repeats. `_evaluate_command` (below)
replaces "grounded in every selected section" with "grounded in the
ACTIVE PROCEDURE section" -- resolved deterministically, never by model
prose -- while still preserving DEF-0024's own universal-safe-command
exception (a command genuinely present in every currently-selected
section is never blocked, regardless of which one is "active", since it
is unambiguously supported either way) and its own fail-closed default
(when no single section can be identified as active, a command that is
not present in every selected section is still rejected).

ACTIVE PROCEDURE RESOLUTION (`resolve_active_section_id`, public since
the 6A.14 Active Procedure Continuity Correction -- see `backend/api/
governed_evidence_continuity.py`'s own `compute_fresh_active_procedure_
anchor`, which reuses this exact function, unmodified, to persist a
cross-turn active-procedure identity from this same turn-local
resolution): a SMALL, deterministic, identity-based rule -- never NLP/
keyword routing, never a semantic "is this relevant" judgment: exactly
one selected section is trivially active; with more than one selected,
the CURRENT incoming request text (`question`/`chat_topic` from THIS
invocation's own `IncidentManagerRequest`, extracted by `_extract_
incoming_question_text`) is checked for a verbatim, case-insensitive
occurrence of exactly ONE candidate's own real section heading -- the
same "compare only against real, already-retrieved governed headings,
never a model suggestion or a fixed vocabulary" discipline `governed_evidence_
continuity.detect_explicit_sibling_topic_override` already established
for a related, but structurally separate, problem (cross-turn topic
override there; same-turn active-section identification here). Zero or
more than one heading match is reported as unresolved (never guessed),
and the caller falls back to DEF-0024's own original all-selected-
sections rule.

TYPED FALLBACK REASON MODEL (`CommandGroundingReason`): the single,
generic `_UNGROUNDED_COMMAND_FALLBACK_TEXT` ("The approved procedure
does not specify a command for this step") was, before this pass,
applied to every rejection uniformly -- including a real, live-observed
case where the active procedure genuinely DOES specify commands, but the
model's own proposed command was a composite/paraphrased string that
failed exact verbatim grounding. Saying "does not specify a command" in
that case is FALSE and actively misleading. `_evaluate_command` now also
returns WHY a command was rejected (never inferred from the final
rendered text -- a typed enum member, decided from the same identity/
content signals the grounding check itself already used), and
`_capture_and_render_troubleshooting_guidance` selects the fallback text
that actually matches: `TRUE_ABSENCE` (the active section's own content
shares no meaningful token overlap with what was proposed -- a generic,
deterministic token-overlap check, never a semantic judgment, mirroring
this codebase's own established 5.1G `TokenOverlapRelevanceScorer`
philosophy) keeps the original wording; `GROUNDING_REJECTED` (the active
section's content DOES share meaningful overlap with what was proposed --
i.e. it plausibly contains a real, related command, just not the exact
one offered) uses new wording that never claims no command exists;
`AMBIGUOUS_PROCEDURE` (no single active section could be identified, and
the proposed command is not universally grounded in every selected
section) asks which governed procedure is meant. A fourth member,
`MISSING_CONDITION`, is deliberately never assigned by this module's own
code -- it names the SAFE, WELL-BEHAVED state where the model itself
correctly leaves `command` unset and asks for the missing condition
(e.g. which specific unit is affected) via `next_action`/`evidence_
requested`, per the new CONDITIONAL COMMAND HANDLING prompt paragraph
(incident_manager/prompts.py) -- there is nothing to strip in that case,
so no fallback text is ever appended; the member exists purely so
calling code and tests can name this expected outcome by the same
typed vocabulary as the three rejection reasons.

LIVE-CORR-4 CORRECTIVE PASS (DEF-0045 -- Free-Text Operational Content
Authority Boundary): a REAL, live-confirmed gap found during DEF-0041's
final live isolation -- the STRUCTURED `command`/`step.command` safety
net (DEF-0024/0026/0027/LIVE-CORR-3A/LIVE-CORR-3B, all above) can be
working perfectly (correctly rejecting/stripping a command) while the
EXACT SAME verbatim command string still reaches the user through a
free-text narrative field (`TroubleshootingStep.action`, confirmed live
in an UNRELATED step; by the same reasoning `interpretation`/`next_
action`/`evidence_requested` for NEXT_STEP guidance) that no existing
mechanism ever inspected. `_scrub_narrative_operational_leaks` closes
this: it compares every narrative field against the SMALL, closed set of
command strings THIS SAME turn's own grounding has ALREADY rejected
(never a new free-text/NLP/regex/keyword judgment of what "looks like a
command") and replaces any contaminated field wholesale with a fixed
safe sentence -- never a partial edit, since a substring match cannot
distinguish a prohibition from an instruction. Wired into `enforce_
procedure_scoped_command_grounding_with_reason` immediately after each
existing per-step/per-guidance rejection point, for both FULL_PROCEDURE
and NEXT_STEP.
"""
from __future__ import annotations

import json
import logging
from enum import Enum
from typing import AbstractSet, Any, Optional, Sequence

from google.genai import types

from backend.agents.incident_manager.provenance_compliance import enforce_governed_knowledge_selection
from backend.agents.incident_manager.schemas import TroubleshootingGuidance, TroubleshootingInteractionMode, TroubleshootingOperationalEffect
from backend.api.turn_context import current_run_id
from backend.tools.teams.get_messages import read_known_message_ids

_logger = logging.getLogger(__name__)

_INCOMING_REQUEST_AUTHOR = "user"


def _find_incoming_request_text(callback_context: Any) -> Optional[str]:
    """A5 final corrective pass (Correction D): the JSON text of THIS
    invocation's own incoming `IncidentManagerRequest` -- `ReadonlyContext
    .user_content` (a public, documented ADK property `MultimodalAgentTool`
    already relies on for the identical "this invocation's own top-level
    Content" guarantee) is exactly the nested `Content` `AgentTool.run_
    async` builds from `input_schema.model_validate(args).model_dump_
    json()`, so its own text part(s) are the request's JSON serialization
    -- never incident_manager's own reply, never a later turn.
    """
    user_content = getattr(callback_context, "user_content", None)
    parts = getattr(user_content, "parts", None) if user_content else None
    if not parts:
        return None
    text = "".join(part.text for part in parts if getattr(part, "text", None))
    return text or None


def _extract_incoming_question_text(callback_context: Any) -> Optional[str]:
    """DEF-0027 corrective pass: the trusted `chat_topic`/`question` text
    of THIS invocation's own incoming `IncidentManagerRequest` -- used
    ONLY for active-procedure heading resolution (`_resolve_active_
    section_id`), never for routing/selection itself. Reuses `_find_
    incoming_request_text`'s own proven "this invocation's real top-level
    Content" guarantee, then parses it the same tolerant, fail-closed way
    `capture_known_applicability_context` already does -- malformed/
    unparseable input, or a request with neither field set, safely
    resolves to `None` (active-procedure resolution then falls back to
    DEF-0024's own original all-selected-sections rule, never a guess).
    """
    text = _find_incoming_request_text(callback_context)
    if not text:
        return None
    try:
        payload = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return None
    if not isinstance(payload, dict):
        return None
    parts = [payload.get("chat_topic"), payload.get("question")]
    combined = " ".join(part for part in parts if isinstance(part, str) and part)
    return combined or None


async def capture_known_applicability_context(callback_context: Any) -> Optional[types.Content]:
    """ADK `before_agent_callback` for `incident_manager` (A5 final
    corrective pass, Correction D) -- registers this turn's trusted
    `known_applicability_facts` (if any) into the run-scoped store
    (`backend.api.applicability_context_capture`) BEFORE any tool call
    happens, so `knowledge_search`'s first call already sees it. ALWAYS
    returns `None` -- per ADK's own contract, a non-`None` return here
    would SKIP the agent's real turn entirely, which this callback must
    never do; it exists purely for this one side effect.

    Never raises: unparseable/malformed input, or a `known_applicability_
    facts` value that fails `normalize_applicability_dimensions`'s own
    structural validation (e.g. a blank key), is treated as "nothing to
    register" -- the turn proceeds with an empty ApplicabilityContext,
    exactly the pre-existing, safe behavior, never a hard failure over a
    side channel.
    """
    from backend.api.applicability_context_capture import register_known_applicability_context
    from backend.knowledge.domain.applicability import ApplicabilityContext

    text = _find_incoming_request_text(callback_context)
    if not text:
        return None
    try:
        payload = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return None
    if not isinstance(payload, dict):
        return None

    raw_facts = payload.get("known_applicability_facts")
    if not raw_facts or not isinstance(raw_facts, dict):
        return None

    try:
        # ApplicabilityContext's own model_validator normalizes/validates
        # `dimensions` (the exact same `normalize_applicability_dimensions`
        # function `Applicability` itself uses) -- no separate call needed.
        context = ApplicabilityContext(dimensions=raw_facts)
    except Exception:
        return None

    register_known_applicability_context(current_run_id(), context)
    return None

_INCIDENT_MANAGER_AUTHOR = "incident_manager"


def validate_evidence(
    evidence: list[Any], known_message_ids: AbstractSet[str]
) -> list[Any]:
    """Return only the entries of `evidence` whose `message_id` is in
    `known_message_ids`. Order is preserved; malformed entries (not a
    dict, or missing `message_id`) are dropped rather than raising -- an
    invented or malformed entry is treated the same as an invented id: it
    does not survive.
    """
    validated = []
    for item in evidence:
        if isinstance(item, dict) and item.get("message_id") in known_message_ids:
            validated.append(item)
    return validated


def _find_last_response_text(session: Any) -> Optional[str]:
    """The text of the most recent event authored by incident_manager
    itself in this (nested, per-call) session -- i.e. its own final
    structured reply, before any correction from this callback.
    """
    for event in reversed(getattr(session, "events", [])):
        if getattr(event, "author", None) != _INCIDENT_MANAGER_AUTHOR:
            continue
        content = getattr(event, "content", None)
        parts = getattr(content, "parts", None) if content else None
        if not parts:
            continue
        text = "".join(part.text for part in parts if getattr(part, "text", None))
        if text:
            return text
    return None


def _strip_evidence_from_text(text: str, known_ids: AbstractSet[str]) -> Optional[str]:
    """Pure text -> text transform, extracted from `strip_unverified_
    evidence` (unchanged behavior) so `enforce_incident_manager_response_
    integrity` (below) can apply the SAME check to text that did not
    necessarily come from `callback_context.session` (e.g. a governed-
    knowledge provenance-compliance retry's own result). Returns the
    corrected JSON text, or `None` when there is nothing to parse, nothing
    to validate, or nothing that actually needed removal.
    """
    try:
        payload = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return None

    if not isinstance(payload, dict):
        return None

    evidence = payload.get("evidence")
    if not isinstance(evidence, list) or not evidence:
        return None

    validated = validate_evidence(evidence, known_ids)
    if validated == evidence:
        return None

    payload["evidence"] = validated
    return json.dumps(payload)


_UNGROUNDED_COMMAND_FALLBACK_TEXT = "The approved procedure does not specify a command for this step."
"""DEF-0024 corrective pass: a FIXED, deterministic, alarm/vendor/
document-independent fallback sentence -- never model-generated, never
templated with any operational-content variable -- used for the
`CommandGroundingReason.TRUE_ABSENCE` case only (DEF-0027). Matches this
codebase's own established pattern of a fixed safe-failure string (e.g.
`provenance_compliance.py`'s `_SAFE_FAILURE_TEXT`) rather than letting
the model author its own explanation for why no command is being shown.
"""

_GROUNDING_REJECTED_FALLBACK_TEXT = (
    "An exact approved command for this step could not yet be safely validated, so it has been withheld."
)
"""DEF-0027 corrective pass: used for `CommandGroundingReason.GROUNDING_
REJECTED` -- deliberately never says "does not specify a command" (that
claim would be false: the active procedure's own content plausibly DOES
contain a real command, it is the model's specific proposal that did not
match it exactly, e.g. a composite/paraphrased/combined string)."""

_AMBIGUOUS_PROCEDURE_FALLBACK_TEXT = (
    "I could not determine which approved procedure this step applies to, so no command is being shown. "
    "Please confirm which governed procedure you mean."
)
"""DEF-0027 corrective pass: used for `CommandGroundingReason.AMBIGUOUS_
PROCEDURE` -- more than one selected section this turn, and no single one
could be deterministically identified as the active procedure, and the
proposed command is not universally grounded in every selected section
(DEF-0024's own preserved safe exception)."""

_CROSS_PROCEDURE_EVIDENCE_FALLBACK_TEXT = (
    "This request touched more than one governed procedure, and I could not safely determine a single "
    "procedure to base operational guidance on. Please confirm which governed procedure applies."
)
"""DEF-0027 FINAL corrective pass: used for `CommandGroundingReason.CROSS_
PROCEDURE_EVIDENCE` -- a WHOLE-GUIDANCE suppression (never merely a
`command` rejection), triggered when this turn's own selected governed
evidence spans more than one distinct `knowledge_id` (genuinely different
governed documents) -- see `_guidance_scope_established`'s own docstring
for the full rationale. Distinct wording from `_AMBIGUOUS_PROCEDURE_
FALLBACK_TEXT` (which describes a narrower, single-document, command-only
ambiguity) since the underlying condition and its scope are both
different -- this one covers the ENTIRE response, never only a command."""

_NARRATIVE_OPERATIONAL_LEAK_FALLBACK_TEXT = (
    "Part of this step's description repeated an operational command that could not be safely verified for this "
    "request, so it has been withheld for safety."
)
"""LIVE-CORR-4 -- DEF-0045 corrective pass: used to replace a free-text
narrative field (`TroubleshootingStep.action`, or -- NEXT_STEP mode --
`TroubleshootingGuidance.interpretation`/`next_action`/`evidence_
requested`) found to reproduce, verbatim, a command THIS SAME turn's own
command-grounding already rejected -- see `_scrub_narrative_operational_
leaks`. A FIXED, deterministic, content-independent sentence, never a
partial/surgical edit of the original text -- a substring check cannot
distinguish a prohibition ("do not run X") from an instruction ("run X"),
so the whole contaminated field is replaced rather than leaving a
possibly garbled or misleading remainder."""

_UNSTRUCTURED_STATE_CHANGE_FALLBACK_TEXT = (
    "This step described an operational recommendation without a verified command to back it, so it has been "
    "withheld for safety. Please ask again."
)
_UNVERIFIED_SECTION_REFERENCE_FALLBACK_TEXT = (
    "This step's operational content could not be verified against the currently active governed section, so it "
    "has been withheld for safety. Please ask again."
)
"""LIVE-CORR-3B -- used for `CommandGroundingReason.UNVERIFIED_SECTION_
REFERENCE` -- a WHOLE-GUIDANCE suppression (mirrors `UNSTRUCTURED_STATE_
CHANGE`'s own scope exactly)."""
"""LIVE-CORR-3A -- DEF-0040 corrective pass (SUPERSEDES the removed,
substring-scanning LIVE-CORR-3 mechanism): used for `CommandGroundingReason
.UNSTRUCTURED_STATE_CHANGE` -- a WHOLE-GUIDANCE suppression (mirrors
`CROSS_PROCEDURE_EVIDENCE`'s own scope exactly), triggered when a step/
guidance is classified (or defaults to, per `TroubleshootingOperationalEffect`'s
own "unset means strictest" rule) `STATE_CHANGE_RECOMMENDATION` but
carries no real, grounded `command`/`step.command` -- see `enforce_
structural_operational_integrity`'s own docstring. Per explicit
instruction, operational safety now comes from this TYPED classification
alone, never from scanning free text for embedded command-like content."""


class CommandGroundingReason(str, Enum):
    """DEF-0027 corrective pass -- see this module's own docstring for the
    full design. `MISSING_CONDITION` is never assigned by this module's
    own code (see the docstring) -- included for a complete, typed
    vocabulary callers/tests can reference by name.
    """

    TRUE_ABSENCE = "true_absence"
    MISSING_CONDITION = "missing_condition"
    GROUNDING_REJECTED = "grounding_rejected"
    AMBIGUOUS_PROCEDURE = "ambiguous_procedure"
    CROSS_PROCEDURE_EVIDENCE = "cross_procedure_evidence"
    """DEF-0027 FINAL corrective pass -- the ENTIRE `TroubleshootingGuidance`
    (never only `command`) was suppressed because this turn's own selected
    governed evidence spanned more than one distinct governed document
    (`knowledge_id`), with no deterministic way to confirm any supporting
    document's content was legitimately authorized by the active one. See
    `_guidance_scope_established`."""
    UNSTRUCTURED_STATE_CHANGE = "unstructured_state_change"
    """LIVE-CORR-3A -- DEF-0040 corrective pass -- the ENTIRE
    `TroubleshootingGuidance` was suppressed because a step/guidance
    classified (or defaulting to) `STATE_CHANGE_RECOMMENDATION` carried
    no real, grounded `command`/`step.command` -- a state-changing
    "recommendation" conveyed ONLY through free text is structurally
    rejected. See `enforce_structural_operational_integrity`."""
    UNVERIFIED_SECTION_REFERENCE = "unverified_section_reference"
    """LIVE-CORR-3B -- Operational Authority Boundary, section 5's own
    "ground operational prose" requirement: a step/guidance whose own
    `source_section_id` (a model PROPOSAL) does not match a section
    actually present in this turn's own real, backend-owned selected-
    evidence set, or names a section OTHER than the resolved active
    procedure section, is rejected -- a model-provided section ID is
    never trusted merely because it was populated. See
    `_verify_source_section_reference`."""


def _fallback_text_for_reason(reason: Optional["CommandGroundingReason"]) -> str:
    """Deterministic reason -> fixed text mapping -- never model-authored,
    never templated with operational content. `TRUE_ABSENCE`, `None`, and
    any unrecognized value all fall back to the original, most
    conservative wording (this preserves DEF-0024's own pre-existing
    behavior exactly for every case this pass does not specifically
    reclassify)."""
    if reason == CommandGroundingReason.GROUNDING_REJECTED:
        return _GROUNDING_REJECTED_FALLBACK_TEXT
    if reason == CommandGroundingReason.AMBIGUOUS_PROCEDURE:
        return _AMBIGUOUS_PROCEDURE_FALLBACK_TEXT
    if reason == CommandGroundingReason.UNSTRUCTURED_STATE_CHANGE:
        return _UNSTRUCTURED_STATE_CHANGE_FALLBACK_TEXT
    if reason == CommandGroundingReason.UNVERIFIED_SECTION_REFERENCE:
        return _UNVERIFIED_SECTION_REFERENCE_FALLBACK_TEXT
    if reason == CommandGroundingReason.CROSS_PROCEDURE_EVIDENCE:
        return _CROSS_PROCEDURE_EVIDENCE_FALLBACK_TEXT
    return _UNGROUNDED_COMMAND_FALLBACK_TEXT


def _tokenize(text: str) -> set[str]:
    """Deterministic, generic (non-vendor-specific) whitespace tokenizer
    with light punctuation trimming -- no `re`, no NLP/semantic
    processing. Used ONLY to classify WHY an already-rejected command was
    rejected (`_classify_absence_or_rejection`, below) -- never a factor
    in the underlying safety decision itself (a command is withheld
    either way; only the explanatory wording differs). Mirrors this
    codebase's own established 5.1G `TokenOverlapRelevanceScorer`
    philosophy -- deterministic token overlap, never a semantic judgment.
    """
    _STRIP_CHARS = ".,;:()[]{}\"'"
    return {stripped for token in text.split() if (stripped := token.strip(_STRIP_CHARS))}


def _classify_absence_or_rejection(proposed_command: str, active_content: str) -> "CommandGroundingReason":
    """Distinguishes `TRUE_ABSENCE` ("this section shares nothing at all
    with what was proposed -- the proposal was plausibly borrowed from
    somewhere else entirely, e.g. a sibling procedure") from `GROUNDING_
    REJECTED` ("this section shares real, meaningful content with what
    was proposed -- it plausibly DOES contain a real command, just not
    the exact one offered, e.g. a paraphrase or a composite of more than
    one real command") using generic, deterministic token overlap only.
    """
    if _tokenize(proposed_command) & _tokenize(active_content):
        return CommandGroundingReason.GROUNDING_REJECTED
    return CommandGroundingReason.TRUE_ABSENCE


_CONFIRMATION_TOKEN_DENYLIST = frozenset({"y", "n", "yes", "no", "0", "1", "ok", "true", "false"})
"""DEF-0027 FINAL corrective pass -- a SMALL, deliberately GENERIC
(natural-language confirmation semantics, never vendor/product-specific
operational syntax) denylist of bare confirmation/response tokens that
must never be trusted as an operational command, no matter how trivially
they might satisfy a verbatim-substring grounding check. A single
character like `"y"` is virtually guaranteed to appear as a substring
inside any real governed section's own text (e.g. copied from a captured
terminal/AMOS confirmation transcript reading "confirm restart? y") --
that triviality, not any genuine grounding, is what let a real live
defect through (`"Run:\n\ny"`). Exact match only, after trimming
whitespace and casefolding -- NEVER a substring match against this
denylist, so a real command that merely CONTAINS the letter "y" is never
at risk.

AUDITED AGAINST THE REAL EXISTING COMMAND/TEST CORPUS before finalizing
this rule (per instruction): `"alt"` -- a real, legitimate 3-character
AMOS command already relied upon by this codebase's own existing tests
(`test_evidence_troubleshooting_guidance.py`'s `_next_step_response`
fixture, `command: "alt"`) -- is deliberately NOT in this denylist and
remains fully valid; this rule targets confirmation SEMANTICS (yes/no/
ok/true/false/0/1), never mere shortness. A length-only heuristic was
considered and rejected specifically because it would have wrongly
rejected `"alt"` (see this module's own DEF-0027 FINAL corrective-pass
closure report for the full audit)."""


def _is_confirmation_token(command: str) -> bool:
    """Whole-string check only -- see `_CONFIRMATION_TOKEN_DENYLIST`'s own
    docstring for why this must never be a substring match."""
    return command.strip().casefold() in _CONFIRMATION_TOKEN_DENYLIST


def _guidance_scope_established(knowledge_ids_by_id: dict[str, "str | None"]) -> bool:
    """DEF-0027 FINAL corrective pass -- the WHOLE-GUIDANCE active-
    procedure boundary (never `command`-only). A real, live-observed
    defect proved that scoping `enforce_procedure_scoped_command_
    grounding` to `command`/`step.command` alone was insufficient: a turn
    that selected governed evidence from TWO DIFFERENT governed documents
    (the active "HW Partial Fault" procedure genuinely relevant to the
    question, ALONGSIDE an unrelated Rogers Resource Timeout MOP) still
    let the unrelated document's own operational content (SSH/AMOS steps,
    DUS/Baseband Radio handling, wait-time/escalation instructions) reach
    the user through `interpretation`/`next_action`/`evidence_requested`/
    `TroubleshootingStep.action` -- none of which `command`-scoped
    grounding ever touches, since those fields are free-form prose, not a
    verbatim-checkable string.

    Per instruction, this does NOT attempt any sentence-level/semantic
    verification of that prose (no LLM-based check of what `action`/
    `next_action` actually says) -- the only deterministic signal
    available is DOCUMENT IDENTITY: whether this turn's own selected
    governed evidence spans more than one distinct `knowledge_id` at all.
    Returns `False` (guidance must be suppressed entirely by the caller)
    whenever more than one distinct `knowledge_id` is represented among
    this turn's selected sections -- regardless of whether a `command`
    happens to be present, and regardless of whether an ACTIVE section
    can otherwise be heading-matched via `resolve_active_section_id`
    (heading-matching only ever disambiguates WITHIN one document; it
    says nothing about whether a genuinely different document's own
    content was also allowed to leak into the free-text guidance).

    DELIBERATELY NARROWER than it could be: a SAME-document, multi-
    section ambiguity (e.g. DEF-0024's own VSWR + HW Partial Fault
    co-selection fixture) is NOT affected by this function at all -- that
    scenario is governed entirely by the pre-existing, already-tested
    command-only `AMBIGUOUS_PROCEDURE`/universal-safe-command logic in
    `_evaluate_command`, unchanged by this pass. This function fires
    ONLY on genuine CROSS-DOCUMENT evidence, the exact shape of the real,
    reported live defect -- never widening DEF-0024's own already-
    accepted same-document behavior.
    """
    distinct_knowledge_ids = {kid for kid in knowledge_ids_by_id.values() if kid is not None}
    return len(distinct_knowledge_ids) <= 1


def _effective_operational_effect(
    raw: Optional["TroubleshootingOperationalEffect"],
) -> "TroubleshootingOperationalEffect":
    """LIVE-CORR-3A -- `None` (unclassified) always resolves to
    `STATE_CHANGE_RECOMMENDATION`, the strictest, safest interpretation,
    never the most permissive one -- per `TroubleshootingOperationalEffect`
    's own docstring ("fail closed on missing/malformed guidance")."""
    return raw if raw is not None else TroubleshootingOperationalEffect.STATE_CHANGE_RECOMMENDATION


def enforce_structural_operational_integrity(
    guidance: TroubleshootingGuidance,
) -> tuple[TroubleshootingGuidance, bool, Optional["CommandGroundingReason"]]:
    """LIVE-CORR-3A -- DEF-0040 corrective pass, REPLACING the removed,
    substring-scanning `_detect_embedded_operational_content` (LIVE-CORR-3)
    outright, per explicit instruction ("operational safety must come from
    typed structure... do not replace it with regex, keyword matching or
    free-text command detection").

    THE STRUCTURAL RULE: any step/guidance whose `operational_effect` IS
    (or, being unset, DEFAULTS TO -- see `_effective_operational_effect`)
    `STATE_CHANGE_RECOMMENDATION` MUST carry a real `command`/`step
    .command` -- a state-changing "recommendation" conveyed ONLY through
    free text (`action`/`next_action`/`interpretation`/`evidence_
    requested`), with no structured command backing it, is a STRUCTURAL
    INTEGRITY FAILURE: the ENTIRE guidance is suppressed (mirrors
    `_guidance_scope_established`'s own whole-guidance scope exactly),
    never rendered. This closes the exact confirmed live DEF-0040 shape
    (a real command embedded in `action` prose, `command` itself left
    `None`) WITHOUT inspecting the free text's own CONTENT at all -- the
    decision is made entirely from the TYPED `operational_effect` field
    and whether `command` is populated, never from what the prose says.

    `DIAGNOSTIC_READ`/`OBSERVATION`/`REFERENCE_DESCRIPTION`-classified
    steps/guidance are UNAFFECTED by this rule (no command required) --
    they carry no operational authority requiring one. This function does
    NOT itself verify that a present `command` is grounded/verbatim --
    that remains the EXISTING, separate, unchanged `_evaluate_command`/
    `enforce_procedure_scoped_command_grounding_with_reason` job, called
    afterward.

    Returns `(possibly-suppressed guidance, whether anything was
    suppressed, the typed reason when suppressed)` -- the SAME 3-tuple
    shape `enforce_procedure_scoped_command_grounding_with_reason` uses,
    so callers compose the two checks identically.
    """
    if guidance.interaction_mode == TroubleshootingInteractionMode.FULL_PROCEDURE:
        for step in guidance.full_procedure_steps:
            if _effective_operational_effect(step.operational_effect) == TroubleshootingOperationalEffect.STATE_CHANGE_RECOMMENDATION and not step.command:
                suppressed = guidance.model_copy(
                    update={
                        "interpretation": None,
                        "next_action": None,
                        "command": None,
                        "evidence_requested": None,
                        "full_procedure_steps": [],
                    }
                )
                return suppressed, True, CommandGroundingReason.UNSTRUCTURED_STATE_CHANGE
        return guidance, False, None

    if _effective_operational_effect(guidance.operational_effect) == TroubleshootingOperationalEffect.STATE_CHANGE_RECOMMENDATION and not guidance.command:
        suppressed = guidance.model_copy(
            update={
                "interpretation": None,
                "next_action": None,
                "command": None,
                "evidence_requested": None,
                "full_procedure_steps": [],
            }
        )
        return suppressed, True, CommandGroundingReason.UNSTRUCTURED_STATE_CHANGE
    return guidance, False, None


def resolve_active_section_id(
    question: Optional[str], section_ids: Sequence[str], headings_by_id: dict[str, Optional[str]]
) -> Optional[str]:
    """DEF-0027 corrective pass -- the smallest deterministic ACTIVE
    PROCEDURE resolver. Never NLP/keyword routing, never a semantic
    judgment: exactly one candidate is trivially active regardless of
    `question`; with more than one candidate, `question` (THIS turn's
    own trusted `chat_topic`/`question` text, see `_extract_incoming_
    question_text`) is checked for a verbatim, case-insensitive
    occurrence of exactly ONE candidate's own real, already-retrieved
    section heading -- never a model suggestion, never a fixed
    vocabulary. Returns `None` (unresolved) whenever zero or more than
    one heading matches, or a heading is missing/blank -- the caller
    must then fall back to a safe, non-active-specific rule, never guess.

    PUBLIC since the 6A.14 Active Procedure Continuity Correction: this
    exact function is now also reused, unmodified, by `backend/api/
    governed_evidence_continuity.py`'s `compute_fresh_active_procedure_
    anchor` to persist this same turn-local active-procedure resolution
    as a durable, cross-turn continuity anchor -- never a second,
    parallel resolver.
    """
    if len(section_ids) <= 1:
        return section_ids[0] if section_ids else None

    if not question:
        return None

    question_lower = question.lower()
    matches = [
        section_id
        for section_id in section_ids
        if (heading := headings_by_id.get(section_id)) and heading.lower() in question_lower
    ]
    if len(matches) == 1:
        return matches[0]
    return None


def _verify_source_section_reference(
    source_section_id: Optional[str],
    section_texts_by_id: dict[str, str],
    active_id: Optional[str],
) -> tuple[bool, Optional["CommandGroundingReason"]]:
    """LIVE-CORR-3B -- Operational Authority Boundary, section 5's own
    "ground operational prose" requirement: bind each rendered operational
    step/guidance to its own selected Approved Knowledge section identity.
    A step/guidance's own `source_section_id` is a model PROPOSAL only --
    verified here against the SAME real, run-scoped, backend-owned
    selected-evidence set `_evaluate_command` itself uses
    (`section_texts_by_id`) and, when an active procedure section could be
    deterministically resolved, against that active identity specifically.

    `None` (the field left unset -- the overwhelming majority of turns,
    since this field is brand new and additive) is a complete no-op,
    returning `(True, None)`: no claim was made to verify, so there is
    nothing to reject. This does NOT itself constitute grounding --
    `_evaluate_command`'s own verbatim-content check remains the primary,
    unaffected command-grounding mechanism regardless of this field.

    Rejects:
      - a `source_section_id` naming a section NOT present in this turn's
        own selected evidence at all (unsupported reference);
      - a `source_section_id` naming a DIFFERENT section than the resolved
        active procedure section, when one could be resolved (cross-
        section reference).

    DELIBERATELY NOT ATTEMPTED, per explicit "if the existing Knowledge
    model cannot prove prerequisites/target independence, fail closed and
    document that limitation; do not invent metadata": whether a step's
    own POSITION within `full_procedure_steps` matches the governed
    source's own explicit ordering (the DEF-0042 "reordered/skipped-
    prerequisite" concern) is NOT verified here -- the Knowledge model
    carries no structured, governed step-ordering signal to check against
    without parsing section text (a text/regex parser is explicitly out of
    bounds), so DEF-0042 remains OPEN, unresolved by this mechanism.
    """
    if source_section_id is None:
        return True, None
    if source_section_id not in section_texts_by_id:
        return False, CommandGroundingReason.UNVERIFIED_SECTION_REFERENCE
    if active_id is not None and source_section_id != active_id:
        return False, CommandGroundingReason.UNVERIFIED_SECTION_REFERENCE
    return True, None


def _scrub_narrative_operational_leaks(
    guidance: TroubleshootingGuidance, rejected_commands: AbstractSet[str]
) -> tuple[TroubleshootingGuidance, bool]:
    """LIVE-CORR-4 -- DEF-0045 correction.

    DEF-0045's own live-confirmed shape: a command this turn's own
    grounding (`_evaluate_command`/`_verify_source_section_reference`)
    already REJECTED can still reach the user because the exact same
    verbatim string was ALSO reproduced inside a free-text narrative
    field -- `TroubleshootingStep.action` (confirmed live in an UNRELATED
    step, not only the step the rejected command itself belonged to), or,
    for NEXT_STEP guidance, `interpretation`/`next_action`/`evidence_
    requested` -- none of which `_evaluate_command`/`_verify_source_
    section_reference`/`enforce_structural_operational_integrity` ever
    inspect (they only ever read `command`/`step.command`).

    Per explicit instruction ("no generic text parsing... no regex/
    keyword/command-syntax detection"), this performs NO command-syntax,
    NLP, or negation/sentiment parsing whatsoever -- it is a single,
    exact, deterministic verbatim-substring check against a value THIS
    SAME turn's own trusted grounding decision has ALREADY rejected
    (`rejected_commands`, populated by the caller from real, already-
    computed rejections -- never a new, independent judgment of what
    counts as "command-shaped"). Because a substring check cannot
    distinguish a prohibition ("do not run X") from an instruction
    ("run X"), the ENTIRE contaminated field is replaced by the fixed
    `_NARRATIVE_OPERATIONAL_LEAK_FALLBACK_TEXT` sentence -- never a
    partial/surgical edit that could leave a garbled or misleading
    remainder -- per the explicit "safe over-suppression is preferable to
    leaking an unauthorized command" instruction. Suppression is scoped to
    the smallest trustworthy unit: one step's `action` (FULL_PROCEDURE) or
    one field (NEXT_STEP), never the whole guidance, never unrelated
    steps/fields that do not contain a rejected string.

    A no-op (`(guidance, False)`) whenever `rejected_commands` is empty
    (the overwhelming majority of turns -- this only ever runs after a
    command was already rejected) or no narrative field actually
    reproduces any of them.
    """
    if not rejected_commands:
        return guidance, False

    def _contaminated(text: Optional[str]) -> bool:
        return bool(text) and any(rejected in text for rejected in rejected_commands)

    scrubbed = False

    if guidance.interaction_mode == TroubleshootingInteractionMode.FULL_PROCEDURE:
        new_steps = []
        for step in guidance.full_procedure_steps:
            if _contaminated(step.action):
                new_steps.append(step.model_copy(update={"action": _NARRATIVE_OPERATIONAL_LEAK_FALLBACK_TEXT}))
                scrubbed = True
            else:
                new_steps.append(step)
        if scrubbed:
            guidance = guidance.model_copy(update={"full_procedure_steps": new_steps})
        return guidance, scrubbed

    updates: dict[str, Any] = {}
    for field_name in ("interpretation", "next_action", "evidence_requested"):
        if _contaminated(getattr(guidance, field_name)):
            updates[field_name] = _NARRATIVE_OPERATIONAL_LEAK_FALLBACK_TEXT
            scrubbed = True
    if scrubbed:
        guidance = guidance.model_copy(update=updates)
    return guidance, scrubbed


def _evaluate_command(
    command: str,
    section_texts_by_id: dict[str, str],
    headings_by_id: dict[str, Optional[str]],
    question: Optional[str],
) -> tuple[bool, Optional["CommandGroundingReason"]]:
    """DEF-0027 corrective pass -- the core command-authorization rule,
    replacing DEF-0024's own "grounded in every selected section" default
    with "grounded in the ACTIVE PROCEDURE section" wherever an active
    section can be deterministically identified, while preserving DEF-
    0024's own fail-closed default and its own universal-safe-command
    exception for the genuinely ambiguous case. Returns `(grounded,
    reason_when_not_grounded)` -- `reason` is always `None` when
    `grounded` is `True`.

    DEF-0027 FINAL corrective pass (Fix #3): a bare confirmation/response
    token (see `_is_confirmation_token`) is rejected BEFORE any substring
    check is even attempted -- a trivially short token like `"y"` would
    otherwise satisfy `in` against almost any real section content,
    which is exactly how a real live defect (`"Run:\n\ny"`) got through.
    """
    if _is_confirmation_token(command):
        return False, CommandGroundingReason.GROUNDING_REJECTED

    if not section_texts_by_id:
        return False, CommandGroundingReason.TRUE_ABSENCE

    section_ids = list(section_texts_by_id.keys())
    active_id = resolve_active_section_id(question, section_ids, headings_by_id)
    if active_id is not None:
        active_content = section_texts_by_id[active_id]
        if command in active_content:
            return True, None
        return False, _classify_absence_or_rejection(command, active_content)

    # DEF-0024's own original fail-closed default for a genuinely
    # ambiguous multi-section selection: a command grounded in EVERY
    # currently-selected section is unambiguously safe regardless of
    # which one is "active"; anything less is rejected as AMBIGUOUS_
    # PROCEDURE (never TRUE_ABSENCE/GROUNDING_REJECTED, since neither of
    # those reasons can be determined without a resolved active section).
    contained_in = [section_id for section_id, content in section_texts_by_id.items() if command in content]
    if contained_in and len(contained_in) == len(section_ids):
        return True, None
    return False, CommandGroundingReason.AMBIGUOUS_PROCEDURE


def _log_grounding_decision(
    run_id: Optional[str],
    guidance: TroubleshootingGuidance,
    selected_items: Sequence[Any],
    active_id: Optional[str],
    stripped: bool,
    reason: Optional["CommandGroundingReason"],
) -> None:
    """LIVE-CORR-3 -- DEF-0041 instrumentation (section 16's own explicit
    field list). Purely observational -- never changes any answer,
    routing, retrieval, or source selection; wrapped in a bare `except`
    so a logging failure can never affect the turn. Logs ONLY safe
    identifiers/counts/typed enum values -- never section/command
    CONTENT, never a governed document body, never a secret/URL/credential.
    `selected_identities` is `(knowledge_id, version_label, section_id)`
    triples only -- the exact same identity shape this codebase's own
    provenance/continuity machinery already treats as safe to log
    elsewhere (e.g. `governed_evidence_continuity.py`).
    """
    try:
        _logger.info(
            "troubleshooting_command_grounding run_id=%s interaction_mode=%s selected_count=%d "
            "selected_identities=%s active_section_id=%s command_present=%s stripped=%s reason=%s",
            run_id,
            guidance.interaction_mode.value,
            len(selected_items),
            [(item.reference.knowledge_id, item.reference.version_label, item.section.section_id) for item in selected_items],
            active_id,
            bool(guidance.command) or any(step.command for step in guidance.full_procedure_steps),
            stripped,
            reason.value if reason is not None else None,
        )
    except Exception:
        pass


def enforce_procedure_scoped_command_grounding_with_reason(
    guidance: TroubleshootingGuidance, run_id: Optional[str], question: Optional[str] = None
) -> tuple[TroubleshootingGuidance, bool, Optional["CommandGroundingReason"]]:
    """DEF-0024 corrective pass (Alarm Procedure Granularity &
    Procedure-Scoped Grounding), extended by DEF-0027 (Active-Procedure
    Command Grounding & Conditional Command Handling) -- see this
    module's own docstring for the full design of both. `COMMAND TRUST
    AND PRESERVATION`'s own prompt-level "reproduce verbatim from
    Approved, selected governed knowledge" instruction was, until DEF-
    0024, never CODE-enforced -- a command could be textually genuine
    (real, Approved, unaltered, verbatim) while still belonging to a
    DIFFERENT procedure/section than the one actually active for THIS
    turn (e.g. a sibling alarm procedure coarsely packaged in the same
    `KnowledgeObject`, or merely co-selected as SUPPORTING context). This
    is the deterministic backstop that closes that gap: a command is
    trusted ONLY if it is grounded in THIS run's own genuinely selected
    evidence (`snapshot_selected_knowledge_evidence` -- backend-only,
    populated exclusively by real `knowledge_select_evidence` calls,
    never model-controllable) -- proven by real content, never merely
    claimed. `run_id` uses the SAME trusted `current_run_id()` correlation
    this codebase already relies on everywhere else for this exact
    problem class (Teams evidence, governed-knowledge selection).

    `question` (DEF-0027, optional, backward-compatible default `None`)
    is THIS turn's own trusted `chat_topic`/`question` text, used ONLY
    for active-procedure heading resolution (`_resolve_active_section_
    id`) -- omitting it (or a `None` value) preserves DEF-0024's own
    original behavior exactly (a `None` question can never resolve an
    active section among more than one candidate, so the original
    "grounded in every selected section" rule applies unchanged).

    Returns `(possibly-corrected guidance, whether anything was stripped,
    the typed reason when something was stripped)`. A turn with no
    `command`/`step.command` populated at all (the overwhelming majority)
    is completely unaffected and always returns `(guidance, False, None)`.

    DEF-0027 FINAL corrective pass (Fix #2): BEFORE any command-level
    check, `_guidance_scope_established` gates the ENTIRE guidance
    object against this turn's selected evidence spanning more than one
    distinct governed document -- see that function's own docstring.
    When it fails, every field (`interpretation`/`next_action`/`command`/
    `evidence_requested`/`full_procedure_steps`) is suppressed, not only
    `command` -- closing a real live defect where unrelated operational
    prose (never checked by the command-only grounding below) reached
    the user even though the specific `command` string itself happened
    to be correctly withheld or absent.
    """
    from backend.tools.knowledge.runtime import snapshot_selected_knowledge_evidence

    selected_items = snapshot_selected_knowledge_evidence(run_id) if run_id else []
    section_texts_by_id: dict[str, str] = {item.section.section_id: item.section.content for item in selected_items}
    headings_by_id: dict[str, Optional[str]] = {item.section.section_id: item.section.heading for item in selected_items}
    knowledge_ids_by_id: dict[str, Optional[str]] = {item.section.section_id: item.reference.knowledge_id for item in selected_items}
    # LIVE-CORR-3 -- DEF-0041 instrumentation: a second, pure, side-
    # effect-free call to the SAME active-section resolver `_evaluate_
    # command` uses internally -- purely for logging visibility into
    # exactly what THIS function saw when it ran (candidate for isolating
    # DEF-0041's own still-unresolved live discrepancy), never a second
    # source of truth for any actual grounding decision below.
    active_id_for_logging = resolve_active_section_id(question, list(section_texts_by_id.keys()), headings_by_id)

    if not _guidance_scope_established(knowledge_ids_by_id):
        suppressed = guidance.model_copy(
            update={
                "interpretation": None,
                "next_action": None,
                "command": None,
                "evidence_requested": None,
                "full_procedure_steps": [],
            }
        )
        _log_grounding_decision(run_id, guidance, selected_items, active_id_for_logging, True, CommandGroundingReason.CROSS_PROCEDURE_EVIDENCE)
        return suppressed, True, CommandGroundingReason.CROSS_PROCEDURE_EVIDENCE

    # LIVE-CORR-3A -- DEF-0040 corrective pass: BEFORE the per-command
    # checks below (which only ever inspect `command`/`step.command`),
    # enforce the TYPED structural-integrity rule -- see `enforce_
    # structural_operational_integrity`'s own docstring. REPLACES the
    # removed, substring-scanning LIVE-CORR-3 mechanism outright: safety
    # now comes from the `operational_effect` classification + whether
    # `command` is populated, never from inspecting free-text content.
    guidance, structurally_stripped, structural_reason = enforce_structural_operational_integrity(guidance)
    if structurally_stripped:
        _log_grounding_decision(run_id, guidance, selected_items, active_id_for_logging, True, structural_reason)
        return guidance, True, structural_reason

    if guidance.interaction_mode == TroubleshootingInteractionMode.FULL_PROCEDURE:
        stripped = False
        primary_reason: Optional[CommandGroundingReason] = None
        new_steps = []
        rejected_commands: set[str] = set()
        for step in guidance.full_procedure_steps:
            if not step.command:
                new_steps.append(step)
                continue
            # LIVE-CORR-3B -- section 5's own "ground operational prose"
            # requirement: verify the step's own proposed `source_section_
            # id` BEFORE the existing verbatim-content check -- a step
            # naming a section outside this turn's own selected evidence,
            # or a section other than the resolved active procedure, is
            # rejected regardless of whether its `command` string would
            # otherwise have passed `_evaluate_command`.
            section_ok, section_reason = _verify_source_section_reference(
                step.source_section_id, section_texts_by_id, active_id_for_logging
            )
            if not section_ok:
                rejected_commands.add(step.command)
                new_steps.append(step.model_copy(update={"command": None}))
                stripped = True
                if primary_reason is None:
                    primary_reason = section_reason
                continue
            grounded, reason = _evaluate_command(step.command, section_texts_by_id, headings_by_id, question)
            if grounded:
                new_steps.append(step)
            else:
                rejected_commands.add(step.command)
                new_steps.append(step.model_copy(update={"command": None}))
                stripped = True
                if primary_reason is None:
                    primary_reason = reason
        if rejected_commands:
            # LIVE-CORR-4 -- DEF-0045: a command rejected ABOVE (belonging
            # to ANY step, not only the step being checked) must not still
            # reach the user through a DIFFERENT step's own free-text
            # `action` -- the confirmed live DEF-0045 shape. Scans every
            # step's `action`, not only the step the rejected command
            # itself came from.
            scrub_target = guidance.model_copy(update={"full_procedure_steps": new_steps})
            scrub_target, narrative_scrubbed = _scrub_narrative_operational_leaks(scrub_target, rejected_commands)
            new_steps = scrub_target.full_procedure_steps
            stripped = stripped or narrative_scrubbed
        _log_grounding_decision(run_id, guidance, selected_items, active_id_for_logging, stripped, primary_reason)
        if not stripped:
            return guidance, False, None
        return guidance.model_copy(update={"full_procedure_steps": new_steps}), True, primary_reason

    if not guidance.command:
        _log_grounding_decision(run_id, guidance, selected_items, active_id_for_logging, False, None)
        return guidance, False, None

    # LIVE-CORR-3B -- section 5, the NEXT_STEP-mode counterpart of the
    # FULL_PROCEDURE per-step check above.
    section_ok, section_reason = _verify_source_section_reference(
        guidance.source_section_id, section_texts_by_id, active_id_for_logging
    )
    if not section_ok:
        rejected_command = guidance.command
        corrected, _ = _scrub_narrative_operational_leaks(
            guidance.model_copy(update={"command": None}), frozenset({rejected_command})
        )
        _log_grounding_decision(run_id, guidance, selected_items, active_id_for_logging, True, section_reason)
        return corrected, True, section_reason

    grounded, reason = _evaluate_command(guidance.command, section_texts_by_id, headings_by_id, question)
    _log_grounding_decision(run_id, guidance, selected_items, active_id_for_logging, not grounded, None if grounded else reason)
    if grounded:
        return guidance, False, None
    # LIVE-CORR-4 -- DEF-0045: the rejected `command` must not still reach
    # the user through `interpretation`/`next_action`/`evidence_requested`
    # (the NEXT_STEP-mode counterpart of the FULL_PROCEDURE `action` scrub
    # above).
    rejected_command = guidance.command
    corrected, _ = _scrub_narrative_operational_leaks(
        guidance.model_copy(update={"command": None}), frozenset({rejected_command})
    )
    return corrected, True, reason


def enforce_procedure_scoped_command_grounding(
    guidance: TroubleshootingGuidance, run_id: Optional[str], question: Optional[str] = None
) -> tuple[TroubleshootingGuidance, bool]:
    """Backward-compatible wrapper over `enforce_procedure_scoped_
    command_grounding_with_reason` -- preserves the original DEF-0024
    2-tuple return shape (every existing caller/test unpacks exactly 2
    values) while the richer function above carries the DEF-0027 typed
    reason for callers that need it (`_capture_and_render_troubleshooting_
    guidance`, below)."""
    corrected, stripped, _reason = enforce_procedure_scoped_command_grounding_with_reason(guidance, run_id, question)
    return corrected, stripped


def _capture_and_render_troubleshooting_guidance(text: str, question: Optional[str] = None) -> Optional[str]:
    """A5 final corrective pass: parses `text` (incident_manager's own
    final structured JSON reply) for a populated `troubleshooting_
    guidance` field, registers it into the run-scoped store (`backend.
    api.troubleshooting_guidance_context`) for `chat_service.py`'s later,
    hard completion-boundary override, and -- defense in depth, so
    incident_manager's OWN structured output already reflects the
    bounded text even before that later override runs -- deterministically
    overwrites `payload["summary"]` with the SAME rendered text.

    `question` (DEF-0027 corrective pass, optional, backward-compatible
    default `None`) is THIS turn's own trusted `chat_topic`/`question`
    text (see `_extract_incoming_question_text`), forwarded to
    `enforce_procedure_scoped_command_grounding_with_reason` for active-
    procedure resolution; the typed reason it returns selects which fixed
    fallback sentence is appended when a command is stripped, never the
    single generic "does not specify a command" wording used
    unconditionally before this pass.

    Returns the corrected JSON text, or `None` when there is nothing to
    parse or no `troubleshooting_guidance` was populated (the overwhelming
    majority of turns -- every non-troubleshooting request is completely
    unaffected). Never raises: a malformed/unparseable `troubleshooting_
    guidance` value is treated as "not populated," never a hard failure
    of the whole turn -- ordinary `summary`-based presentation still
    applies in that case.
    """
    from backend.api.troubleshooting_guidance_context import register_troubleshooting_guidance, render_troubleshooting_guidance

    try:
        payload = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return None
    if not isinstance(payload, dict):
        return None

    raw_guidance = payload.get("troubleshooting_guidance")
    if not raw_guidance:
        return None

    try:
        guidance = TroubleshootingGuidance.model_validate(raw_guidance)
    except Exception:
        return None

    run_id = current_run_id()
    guidance, command_was_stripped, reason = enforce_procedure_scoped_command_grounding_with_reason(guidance, run_id, question)
    register_troubleshooting_guidance(run_id, guidance)

    rendered = render_troubleshooting_guidance(guidance)
    if command_was_stripped:
        fallback_text = _fallback_text_for_reason(reason)
        rendered = f"{rendered}\n\n{fallback_text}" if rendered else fallback_text
    if payload.get("summary") == rendered:
        return None
    payload["summary"] = rendered
    return json.dumps(payload)


def strip_unverified_evidence(callback_context: Any) -> Optional[types.Content]:
    """ADK `after_agent_callback` for `incident_manager` -- see the module
    docstring. Returns `None` (no override) whenever there is nothing to
    parse, nothing to validate, or nothing that actually needed removal;
    returns a corrected `types.Content` only when at least one `evidence`
    entry was stripped.
    """
    text = _find_last_response_text(getattr(callback_context, "session", None))
    if not text:
        return None

    known_ids: AbstractSet[str] = read_known_message_ids(callback_context.state)
    corrected_text = _strip_evidence_from_text(text, known_ids)
    if corrected_text is None:
        return None
    return types.Content(role="model", parts=[types.Part.from_text(text=corrected_text)])


async def enforce_incident_manager_response_integrity(callback_context: Any) -> Optional[types.Content]:
    """THIRD pre-4H correction pass -- the combined `after_agent_callback`
    wired onto the LIVE `incident_manager` agent (agent.py) in place of
    `strip_unverified_evidence` alone.

    Runs `provenance_compliance.enforce_governed_knowledge_selection`
    first (governed-knowledge "SEARCH RESULT != EVIDENCE USED"
    enforcement, including its own bounded one-retry mechanism), then
    applies the SAME Teams evidence-stripping check `strip_unverified_
    evidence` already performs to whatever text is final afterward --
    whether that is incident_manager's own original text (the common,
    already-compliant case), the compliance retry's corrected text, or a
    deterministic safe-failure text. This guarantees a combined Teams +
    governed-knowledge answer is validated on BOTH axes, never only one.

    Returns `None` (no override -- incident_manager's own original
    response stands unchanged) whenever neither check needed to intervene.
    """
    original_text = _find_last_response_text(getattr(callback_context, "session", None))
    provenance_text = await enforce_governed_knowledge_selection(callback_context, original_text)
    working_text = provenance_text if provenance_text is not None else original_text
    if not working_text:
        return None

    known_ids: AbstractSet[str] = read_known_message_ids(callback_context.state)
    stripped_text = _strip_evidence_from_text(working_text, known_ids)
    final_text = stripped_text if stripped_text is not None else working_text

    # A5 final corrective pass: runs LAST, on whatever text is final after
    # the existing Teams/governed-knowledge checks above -- captures any
    # troubleshooting_guidance for chat_service.py's completion-boundary
    # override and, as defense in depth, deterministically rewrites
    # `summary` from it right here too. A turn with no troubleshooting_
    # guidance populated (the common case) is completely unaffected.
    # DEF-0027 corrective pass: `_extract_incoming_question_text` reads
    # THIS invocation's own trusted `chat_topic`/`question` for active-
    # procedure resolution -- a `_FakeCallbackContext` (or any context
    # with no `user_content` attribute) safely resolves to `None`,
    # preserving every pre-existing test's behavior exactly.
    guidance_text = _capture_and_render_troubleshooting_guidance(final_text, _extract_incoming_question_text(callback_context))
    if guidance_text is not None:
        final_text = guidance_text

    if final_text == original_text:
        return None
    return types.Content(role="model", parts=[types.Part.from_text(text=final_text)])
