"""Deterministic evidence validation for incident_manager.

"Do not trust arbitrary message IDs generated by the LLM" -- this module
is the enforcement, not just a prompt instruction. `validate_evidence` is
the pure, directly-testable rule: an `evidence` entry survives only if its
`message_id` is in the set of message ids actually retrieved (or actually
present inside a retrieved message's `message_references`) this turn --
see `backend/tools/teams/get_messages.py`'s `KNOWN_MESSAGE_IDS_STATE_KEY`,
which `teams_get_messages` populates as it runs.

`strip_unverified_evidence` wires that rule into the ADK runtime: it
inspects incident_manager's own final structured response (already
produced and validated against `IncidentManagerResponse` by the
model/ADK), re-checks every `evidence[].message_id` against the session's
actual `known_message_ids`, and -- only if something needed to be removed
-- returns a corrected `Content` that ADK treats as this turn's real
final output, which `AgentTool` (docs/AGENT_CONTRACT.md #4) then returns
to team_manager instead of the unverified one. This mirrors the same
philosophy already used for the write-tool approval gate elsewhere in
this codebase: prompt instructions alone are not a sufficient control,
so the guarantee is enforced in deterministic code that runs regardless
of what the model was told or "believed" was true.

This module does NOT attempt semantic validation of whether a message
truly supports a claim -- only that the cited provenance is real,
retrieved Teams data (per the task's explicit instruction not to
second-guess relevance, only existence).

THIRD PRE-4H CORRECTION PASS: `agent.py`'s own `after_agent_callback` is
now `enforce_incident_manager_response_integrity` (below), not
`strip_unverified_evidence` directly -- it runs
`provenance_compliance.enforce_governed_knowledge_selection` FIRST (the
new "SEARCH RESULT != EVIDENCE USED" enforcement -- see that module's own
docstring), then applies this module's existing, UNCHANGED Teams
evidence-stripping check to whatever text is final afterward, so a
corrected combined (Teams + governed knowledge) answer is still subject
to the SAME Teams-evidence validation every other incident_manager turn
already gets. `strip_unverified_evidence` itself is untouched -- still
directly tested, still used unmodified by every OTHER incident_manager
variant that inherits `after_agent_callback` without overriding it and
never sets `requires_governed_knowledge=true` in the first place
(`_CONTINUATION_INCIDENT_MANAGER`/`_SYNTHESIS_ONLY_INCIDENT_MANAGER`,
read_continuation_execution.py).
"""
from __future__ import annotations

import json
from typing import AbstractSet, Any, Optional

from google.genai import types

from backend.agents.incident_manager.provenance_compliance import enforce_governed_knowledge_selection
from backend.agents.incident_manager.schemas import TroubleshootingGuidance
from backend.api.turn_context import current_run_id
from backend.tools.teams.get_messages import KNOWN_MESSAGE_IDS_STATE_KEY

_INCOMING_REQUEST_AUTHOR = "user"


def _find_incoming_request_text(callback_context: Any) -> Optional[str]:
    """A5 final corrective pass (Correction D): the JSON text of THIS
    invocation's own incoming `IncidentManagerRequest` -- `ReadonlyContext
    .user_content` (a public, documented ADK property `MultimodalAgentTool`
    already relies on for the identical "this invocation's own top-level
    Content" guarantee) is exactly the nested `Content` `AgentTool.run_
    async` builds from `input_schema.model_validate(args).model_dump_
    json()`, so its own text part(s) are the request's JSON serialization
    -- never incident_manager's own reply, never a later turn.
    """
    user_content = getattr(callback_context, "user_content", None)
    parts = getattr(user_content, "parts", None) if user_content else None
    if not parts:
        return None
    text = "".join(part.text for part in parts if getattr(part, "text", None))
    return text or None


async def capture_known_applicability_context(callback_context: Any) -> Optional[types.Content]:
    """ADK `before_agent_callback` for `incident_manager` (A5 final
    corrective pass, Correction D) -- registers this turn's trusted
    `known_applicability_facts` (if any) into the run-scoped store
    (`backend.api.applicability_context_capture`) BEFORE any tool call
    happens, so `knowledge_search`'s first call already sees it. ALWAYS
    returns `None` -- per ADK's own contract, a non-`None` return here
    would SKIP the agent's real turn entirely, which this callback must
    never do; it exists purely for this one side effect.

    Never raises: unparseable/malformed input, or a `known_applicability_
    facts` value that fails `normalize_applicability_dimensions`'s own
    structural validation (e.g. a blank key), is treated as "nothing to
    register" -- the turn proceeds with an empty ApplicabilityContext,
    exactly the pre-existing, safe behavior, never a hard failure over a
    side channel.
    """
    from backend.api.applicability_context_capture import register_known_applicability_context
    from backend.knowledge.domain.applicability import ApplicabilityContext

    text = _find_incoming_request_text(callback_context)
    if not text:
        return None
    try:
        payload = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return None
    if not isinstance(payload, dict):
        return None

    raw_facts = payload.get("known_applicability_facts")
    if not raw_facts or not isinstance(raw_facts, dict):
        return None

    try:
        # ApplicabilityContext's own model_validator normalizes/validates
        # `dimensions` (the exact same `normalize_applicability_dimensions`
        # function `Applicability` itself uses) -- no separate call needed.
        context = ApplicabilityContext(dimensions=raw_facts)
    except Exception:
        return None

    register_known_applicability_context(current_run_id(), context)
    return None

_INCIDENT_MANAGER_AUTHOR = "incident_manager"


def validate_evidence(
    evidence: list[Any], known_message_ids: AbstractSet[str]
) -> list[Any]:
    """Return only the entries of `evidence` whose `message_id` is in
    `known_message_ids`. Order is preserved; malformed entries (not a
    dict, or missing `message_id`) are dropped rather than raising -- an
    invented or malformed entry is treated the same as an invented id: it
    does not survive.
    """
    validated = []
    for item in evidence:
        if isinstance(item, dict) and item.get("message_id") in known_message_ids:
            validated.append(item)
    return validated


def _find_last_response_text(session: Any) -> Optional[str]:
    """The text of the most recent event authored by incident_manager
    itself in this (nested, per-call) session -- i.e. its own final
    structured reply, before any correction from this callback.
    """
    for event in reversed(getattr(session, "events", [])):
        if getattr(event, "author", None) != _INCIDENT_MANAGER_AUTHOR:
            continue
        content = getattr(event, "content", None)
        parts = getattr(content, "parts", None) if content else None
        if not parts:
            continue
        text = "".join(part.text for part in parts if getattr(part, "text", None))
        if text:
            return text
    return None


def _strip_evidence_from_text(text: str, known_ids: AbstractSet[str]) -> Optional[str]:
    """Pure text -> text transform, extracted from `strip_unverified_
    evidence` (unchanged behavior) so `enforce_incident_manager_response_
    integrity` (below) can apply the SAME check to text that did not
    necessarily come from `callback_context.session` (e.g. a governed-
    knowledge provenance-compliance retry's own result). Returns the
    corrected JSON text, or `None` when there is nothing to parse, nothing
    to validate, or nothing that actually needed removal.
    """
    try:
        payload = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return None

    if not isinstance(payload, dict):
        return None

    evidence = payload.get("evidence")
    if not isinstance(evidence, list) or not evidence:
        return None

    validated = validate_evidence(evidence, known_ids)
    if validated == evidence:
        return None

    payload["evidence"] = validated
    return json.dumps(payload)


def _capture_and_render_troubleshooting_guidance(text: str) -> Optional[str]:
    """A5 final corrective pass: parses `text` (incident_manager's own
    final structured JSON reply) for a populated `troubleshooting_
    guidance` field, registers it into the run-scoped store (`backend.
    api.troubleshooting_guidance_context`) for `chat_service.py`'s later,
    hard completion-boundary override, and -- defense in depth, so
    incident_manager's OWN structured output already reflects the
    bounded text even before that later override runs -- deterministically
    overwrites `payload["summary"]` with the SAME rendered text.

    Returns the corrected JSON text, or `None` when there is nothing to
    parse or no `troubleshooting_guidance` was populated (the overwhelming
    majority of turns -- every non-troubleshooting request is completely
    unaffected). Never raises: a malformed/unparseable `troubleshooting_
    guidance` value is treated as "not populated," never a hard failure
    of the whole turn -- ordinary `summary`-based presentation still
    applies in that case.
    """
    from backend.api.troubleshooting_guidance_context import register_troubleshooting_guidance, render_troubleshooting_guidance

    try:
        payload = json.loads(text)
    except (json.JSONDecodeError, TypeError):
        return None
    if not isinstance(payload, dict):
        return None

    raw_guidance = payload.get("troubleshooting_guidance")
    if not raw_guidance:
        return None

    try:
        guidance = TroubleshootingGuidance.model_validate(raw_guidance)
    except Exception:
        return None

    register_troubleshooting_guidance(current_run_id(), guidance)

    rendered = render_troubleshooting_guidance(guidance)
    if payload.get("summary") == rendered:
        return None
    payload["summary"] = rendered
    return json.dumps(payload)


def strip_unverified_evidence(callback_context: Any) -> Optional[types.Content]:
    """ADK `after_agent_callback` for `incident_manager` -- see the module
    docstring. Returns `None` (no override) whenever there is nothing to
    parse, nothing to validate, or nothing that actually needed removal;
    returns a corrected `types.Content` only when at least one `evidence`
    entry was stripped.
    """
    text = _find_last_response_text(getattr(callback_context, "session", None))
    if not text:
        return None

    known_ids: AbstractSet[str] = set(
        callback_context.state.get(KNOWN_MESSAGE_IDS_STATE_KEY, [])
    )
    corrected_text = _strip_evidence_from_text(text, known_ids)
    if corrected_text is None:
        return None
    return types.Content(role="model", parts=[types.Part.from_text(text=corrected_text)])


async def enforce_incident_manager_response_integrity(callback_context: Any) -> Optional[types.Content]:
    """THIRD pre-4H correction pass -- the combined `after_agent_callback`
    wired onto the LIVE `incident_manager` agent (agent.py) in place of
    `strip_unverified_evidence` alone.

    Runs `provenance_compliance.enforce_governed_knowledge_selection`
    first (governed-knowledge "SEARCH RESULT != EVIDENCE USED"
    enforcement, including its own bounded one-retry mechanism), then
    applies the SAME Teams evidence-stripping check `strip_unverified_
    evidence` already performs to whatever text is final afterward --
    whether that is incident_manager's own original text (the common,
    already-compliant case), the compliance retry's corrected text, or a
    deterministic safe-failure text. This guarantees a combined Teams +
    governed-knowledge answer is validated on BOTH axes, never only one.

    Returns `None` (no override -- incident_manager's own original
    response stands unchanged) whenever neither check needed to intervene.
    """
    original_text = _find_last_response_text(getattr(callback_context, "session", None))
    provenance_text = await enforce_governed_knowledge_selection(callback_context, original_text)
    working_text = provenance_text if provenance_text is not None else original_text
    if not working_text:
        return None

    known_ids: AbstractSet[str] = set(
        callback_context.state.get(KNOWN_MESSAGE_IDS_STATE_KEY, [])
    )
    stripped_text = _strip_evidence_from_text(working_text, known_ids)
    final_text = stripped_text if stripped_text is not None else working_text

    # A5 final corrective pass: runs LAST, on whatever text is final after
    # the existing Teams/governed-knowledge checks above -- captures any
    # troubleshooting_guidance for chat_service.py's completion-boundary
    # override and, as defense in depth, deterministically rewrites
    # `summary` from it right here too. A turn with no troubleshooting_
    # guidance populated (the common case) is completely unaffected.
    guidance_text = _capture_and_render_troubleshooting_guidance(final_text)
    if guidance_text is not None:
        final_text = guidance_text

    if final_text == original_text:
        return None
    return types.Content(role="model", parts=[types.Part.from_text(text=final_text)])
