"""chat attachments table

Revision ID: 3e59584b1012
Revises: b85242503972
Create Date: 2026-09-07 20:00:46.966827

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e59584b1012'
down_revision: Union[str, None] = 'b85242503972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slopanoc_chat_attachments',
    sa.Column('attachment_id', sa.String(), nullable=False),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('storage_object_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(mime_type) > 0', name='ck_slopanoc_chat_attachments_mime_type_nonempty'),
    sa.CheckConstraint('length(original_filename) > 0', name='ck_slopanoc_chat_attachments_filename_nonempty'),
    sa.CheckConstraint('length(sha256) > 0', name='ck_slopanoc_chat_attachments_sha256_nonempty'),
    sa.CheckConstraint('length(storage_object_name) > 0', name='ck_slopanoc_chat_attachments_storage_object_name_nonempty'),
    sa.CheckConstraint('size_bytes > 0', name='ck_slopanoc_chat_attachments_size_bytes_positive'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_index('ix_slopanoc_chat_attachments_owner_session', 'slopanoc_chat_attachments', ['owner_user_id', 'session_id'], unique=False)
    op.create_index('ix_slopanoc_chat_attachments_session_message', 'slopanoc_chat_attachments', ['session_id', 'message_id'], unique=False)
    op.create_index('ix_slopanoc_chat_attachments_status_created', 'slopanoc_chat_attachments', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_slopanoc_chat_attachments_status_created', table_name='slopanoc_chat_attachments')
    op.drop_index('ix_slopanoc_chat_attachments_session_message', table_name='slopanoc_chat_attachments')
    op.drop_index('ix_slopanoc_chat_attachments_owner_session', table_name='slopanoc_chat_attachments')
    op.drop_table('slopanoc_chat_attachments')
    # ### end Alembic commands ###
