"""Add bounded operational observability storage; never ADK schema."""
from alembic import op
import sqlalchemy as sa
revision = '9f71c2a64e08'
down_revision = '7c4e9a2d1f05'
branch_labels = None
depends_on = None

def upgrade():
    op.create_table('observability_run_event',
        sa.Column('run_id', sa.String(36), nullable=False, primary_key=True),
        sa.Column('event_seq', sa.BigInteger(), nullable=False, primary_key=True),
        sa.Column('state_version', sa.BigInteger(), nullable=False, primary_key=False),
        sa.Column('event_type', sa.String(16), nullable=False, primary_key=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, primary_key=False),
        sa.Column('elapsed_ms', sa.Float(), nullable=False, primary_key=False),
        sa.Column('stage', sa.String(64), nullable=False, primary_key=False),
        sa.Column('status', sa.String(16), nullable=False, primary_key=False),
        sa.Column('agent', sa.String(64), nullable=True, primary_key=False),
        sa.Column('tool', sa.String(64), nullable=True, primary_key=False),
        sa.Column('dependency', sa.String(64), nullable=True, primary_key=False),
        sa.Column('error_code', sa.String(64), nullable=True, primary_key=False),
        sa.CheckConstraint('event_seq >= 0 AND state_version >= 0 AND elapsed_ms >= 0'),
        sa.CheckConstraint("event_type IN ('started','stage','agent','tool','dependency','stalled','resumed','terminal','cleanup','delivery','identity','deadline')"),
        sa.CheckConstraint("stage IN ('request.received','request.validated','session.load.started','session.load.completed','attachments.started','attachments.completed','planning.started','planning.model.started','planning.model.completed','planning.completed','planning.failed','thread.resolve.started','thread.resolve.completed','pending_interaction.resolve.started','pending_interaction.resolve.completed','source_requirements.completed','context.selection.started','context.selection.completed','context.item.selected','context.item.excluded','agent.started','agent.completed','agent.failed','agent.team_manager','agent.technical_authority','agent.incident_manager','agent.problem_manager','agent.automated_operations','model.request.started','model.first_token','model.request.completed','model.request.failed','model.request.timeout','tool.started','tool.completed','tool.failed','tool.timeout','knowledge.search.started','knowledge.search.completed','teams.list_chats.started','teams.list_chats.completed','teams.read_messages.started','teams.read_messages.completed','database.query.started','database.query.completed','storage.operation.started','storage.operation.completed','knowledge.selection.completed','procedure_action.resolved','command_authority.completed','approval.requested','approval.completed','authority.selected','provenance.completed','command_egress.completed','synthesis.started','synthesis.completed','persistence.started','persistence.completed','sse.started','sse.completed','turn.completed','turn.failed','turn.timeout','turn.cancelled','run.stalled','heartbeat')"),
        sa.CheckConstraint("status IN ('PENDING','RUNNING','COMPLETED','FAILED','TIMEOUT','CANCELLED','STALLED')"),
    )
    op.create_table('observability_run_status',
        sa.Column('current_span_id', sa.String(16), nullable=True, primary_key=False),
        sa.Column('current_agent', sa.String(64), nullable=True, primary_key=False),
        sa.Column('current_tool', sa.String(64), nullable=True, primary_key=False),
        sa.Column('dependencies', sa.JSON(), nullable=False, primary_key=False),
        sa.Column('stage_started_at', sa.DateTime(timezone=True), nullable=False, primary_key=False),
        sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=False, primary_key=False),
        sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False, primary_key=False),
        sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False, primary_key=False),
        sa.Column('work_deadline_at', sa.DateTime(timezone=True), nullable=True, primary_key=False),
        sa.Column('total_deadline_at', sa.DateTime(timezone=True), nullable=True, primary_key=False),
        sa.Column('stalled', sa.Boolean(), nullable=False, primary_key=False),
        sa.Column('stalled_at', sa.DateTime(timezone=True), nullable=True, primary_key=False),
        sa.Column('run_id', sa.String(36), nullable=False, primary_key=True),
        sa.Column('producer_instance_id', sa.String(36), nullable=False, primary_key=False),
        sa.Column('state_version', sa.BigInteger(), nullable=False, primary_key=False),
        sa.Column('session_detached', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('session_id', sa.String(128), nullable=True, primary_key=False),
        sa.Column('turn_id', sa.String(128), nullable=True, primary_key=False),
        sa.Column('turn_id_origin', sa.String(16), nullable=True, primary_key=False),
        sa.Column('trace_id', sa.String(32), nullable=True, primary_key=False),
        sa.Column('root_span_id', sa.String(16), nullable=True, primary_key=False),
        sa.Column('environment', sa.String(64), nullable=False, primary_key=False),
        sa.Column('status', sa.String(16), nullable=False, primary_key=False),
        sa.Column('current_stage', sa.String(64), nullable=False, primary_key=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, primary_key=False),
        sa.Column('terminal_at', sa.DateTime(timezone=True), nullable=True, primary_key=False),
        sa.Column('elapsed_ms', sa.Float(), nullable=False, primary_key=False),
        sa.Column('error_code', sa.String(64), nullable=True, primary_key=False),
        sa.Column('error_stage', sa.String(64), nullable=True, primary_key=False),
        sa.Column('cleanup_status', sa.String(16), nullable=False, primary_key=False),
        sa.Column('delivery_status', sa.String(16), nullable=False, primary_key=False),
        sa.Column('service_version', sa.String(64), nullable=True, primary_key=False),
        sa.Column('git_sha', sa.String(64), nullable=True, primary_key=False),
        sa.Column('release_id', sa.String(64), nullable=True, primary_key=False),
        sa.Column('revision', sa.String(64), nullable=True, primary_key=False),
        sa.Column('region', sa.String(64), nullable=True, primary_key=False),
        sa.Column('config_version', sa.String(16), nullable=True, primary_key=False),
        sa.Column('telemetry_schema_version', sa.Integer(), nullable=False, primary_key=False),
        sa.Column('projection_schema_version', sa.Integer(), nullable=False, primary_key=False),
        sa.Column('retention_class', sa.String(16), nullable=False, primary_key=False),
        sa.Column('ever_stalled', sa.Boolean(), nullable=False, primary_key=False),
        sa.Column('timeline_truncated_count', sa.BigInteger(), nullable=False, primary_key=False),
        sa.Column('expiry_at', sa.DateTime(timezone=True), nullable=False, primary_key=False),
        sa.CheckConstraint("(status IN ('COMPLETED','FAILED','TIMEOUT','CANCELLED') AND terminal_at IS NOT NULL) OR (status IN ('PENDING','RUNNING','STALLED') AND terminal_at IS NULL)"),
        sa.CheckConstraint("cleanup_status IN ('pending','running','completed','failed','timeout')"),
        sa.CheckConstraint("current_stage IN ('request.received','request.validated','session.load.started','session.load.completed','attachments.started','attachments.completed','planning.started','planning.model.started','planning.model.completed','planning.completed','planning.failed','thread.resolve.started','thread.resolve.completed','pending_interaction.resolve.started','pending_interaction.resolve.completed','source_requirements.completed','context.selection.started','context.selection.completed','context.item.selected','context.item.excluded','agent.started','agent.completed','agent.failed','agent.team_manager','agent.technical_authority','agent.incident_manager','agent.problem_manager','agent.automated_operations','model.request.started','model.first_token','model.request.completed','model.request.failed','model.request.timeout','tool.started','tool.completed','tool.failed','tool.timeout','knowledge.search.started','knowledge.search.completed','teams.list_chats.started','teams.list_chats.completed','teams.read_messages.started','teams.read_messages.completed','database.query.started','database.query.completed','storage.operation.started','storage.operation.completed','knowledge.selection.completed','procedure_action.resolved','command_authority.completed','approval.requested','approval.completed','authority.selected','provenance.completed','command_egress.completed','synthesis.started','synthesis.completed','persistence.started','persistence.completed','sse.started','sse.completed','turn.completed','turn.failed','turn.timeout','turn.cancelled','run.stalled','heartbeat')"),
        sa.CheckConstraint("delivery_status IN ('pending','relayed','disconnected')"),
        sa.CheckConstraint("retention_class IN ('normal','exceptional')"),
        sa.CheckConstraint('state_version >= 0 AND elapsed_ms >= 0 AND timeline_truncated_count >= 0'),
        sa.CheckConstraint("status IN ('PENDING','RUNNING','COMPLETED','FAILED','TIMEOUT','CANCELLED','STALLED')"),
        sa.CheckConstraint("status NOT IN ('COMPLETED','FAILED','TIMEOUT','CANCELLED') OR (current_agent IS NULL AND current_tool IS NULL)"),
        sa.CheckConstraint('telemetry_schema_version = 1 AND projection_schema_version = 1'),
    )
    op.create_index('ix_observability_active', 'observability_run_status', ['environment', 'status', 'heartbeat_at', 'run_id'])
    op.create_index('ix_observability_session', 'observability_run_status', ['session_id', 'started_at', 'run_id'])
    op.create_index('ix_observability_status_expiry', 'observability_run_status', ['expiry_at', 'run_id'])
    op.create_table('observability_turn',
        sa.Column('run_id', sa.String(36), nullable=False, primary_key=True),
        sa.Column('producer_instance_id', sa.String(36), nullable=False, primary_key=False),
        sa.Column('state_version', sa.BigInteger(), nullable=False, primary_key=False),
        sa.Column('session_detached', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column('session_id', sa.String(128), nullable=True, primary_key=False),
        sa.Column('turn_id', sa.String(128), nullable=True, primary_key=False),
        sa.Column('turn_id_origin', sa.String(16), nullable=True, primary_key=False),
        sa.Column('trace_id', sa.String(32), nullable=True, primary_key=False),
        sa.Column('root_span_id', sa.String(16), nullable=True, primary_key=False),
        sa.Column('environment', sa.String(64), nullable=False, primary_key=False),
        sa.Column('status', sa.String(16), nullable=False, primary_key=False),
        sa.Column('current_stage', sa.String(64), nullable=False, primary_key=False),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, primary_key=False),
        sa.Column('terminal_at', sa.DateTime(timezone=True), nullable=True, primary_key=False),
        sa.Column('elapsed_ms', sa.Float(), nullable=False, primary_key=False),
        sa.Column('error_code', sa.String(64), nullable=True, primary_key=False),
        sa.Column('error_stage', sa.String(64), nullable=True, primary_key=False),
        sa.Column('cleanup_status', sa.String(16), nullable=False, primary_key=False),
        sa.Column('delivery_status', sa.String(16), nullable=False, primary_key=False),
        sa.Column('service_version', sa.String(64), nullable=True, primary_key=False),
        sa.Column('git_sha', sa.String(64), nullable=True, primary_key=False),
        sa.Column('release_id', sa.String(64), nullable=True, primary_key=False),
        sa.Column('revision', sa.String(64), nullable=True, primary_key=False),
        sa.Column('region', sa.String(64), nullable=True, primary_key=False),
        sa.Column('config_version', sa.String(16), nullable=True, primary_key=False),
        sa.Column('telemetry_schema_version', sa.Integer(), nullable=False, primary_key=False),
        sa.Column('projection_schema_version', sa.Integer(), nullable=False, primary_key=False),
        sa.Column('retention_class', sa.String(16), nullable=False, primary_key=False),
        sa.Column('ever_stalled', sa.Boolean(), nullable=False, primary_key=False),
        sa.Column('timeline_truncated_count', sa.BigInteger(), nullable=False, primary_key=False),
        sa.Column('expiry_at', sa.DateTime(timezone=True), nullable=False, primary_key=False),
        sa.CheckConstraint("(status IN ('COMPLETED','FAILED','TIMEOUT','CANCELLED') AND terminal_at IS NOT NULL) OR (status IN ('PENDING','RUNNING','STALLED') AND terminal_at IS NULL)"),
        sa.CheckConstraint("cleanup_status IN ('pending','running','completed','failed','timeout')"),
        sa.CheckConstraint("current_stage IN ('request.received','request.validated','session.load.started','session.load.completed','attachments.started','attachments.completed','planning.started','planning.model.started','planning.model.completed','planning.completed','planning.failed','thread.resolve.started','thread.resolve.completed','pending_interaction.resolve.started','pending_interaction.resolve.completed','source_requirements.completed','context.selection.started','context.selection.completed','context.item.selected','context.item.excluded','agent.started','agent.completed','agent.failed','agent.team_manager','agent.technical_authority','agent.incident_manager','agent.problem_manager','agent.automated_operations','model.request.started','model.first_token','model.request.completed','model.request.failed','model.request.timeout','tool.started','tool.completed','tool.failed','tool.timeout','knowledge.search.started','knowledge.search.completed','teams.list_chats.started','teams.list_chats.completed','teams.read_messages.started','teams.read_messages.completed','database.query.started','database.query.completed','storage.operation.started','storage.operation.completed','knowledge.selection.completed','procedure_action.resolved','command_authority.completed','approval.requested','approval.completed','authority.selected','provenance.completed','command_egress.completed','synthesis.started','synthesis.completed','persistence.started','persistence.completed','sse.started','sse.completed','turn.completed','turn.failed','turn.timeout','turn.cancelled','run.stalled','heartbeat')"),
        sa.CheckConstraint("delivery_status IN ('pending','relayed','disconnected')"),
        sa.CheckConstraint("retention_class IN ('normal','exceptional')"),
        sa.CheckConstraint('state_version >= 0 AND elapsed_ms >= 0 AND timeline_truncated_count >= 0'),
        sa.CheckConstraint("status IN ('COMPLETED','FAILED','TIMEOUT','CANCELLED')"),
        sa.CheckConstraint("status IN ('PENDING','RUNNING','COMPLETED','FAILED','TIMEOUT','CANCELLED','STALLED')"),
        sa.CheckConstraint('telemetry_schema_version = 1 AND projection_schema_version = 1'),
    )
    op.create_index('ix_observability_recent', 'observability_turn', ['environment', 'started_at', 'run_id'])
    op.create_index('ix_observability_summary_expiry', 'observability_turn', ['expiry_at', 'run_id'])
    op.create_index('ix_observability_summary_session', 'observability_turn', ['session_id', 'started_at', 'run_id'])
    op.create_index('ix_observability_terminal', 'observability_turn', ['environment', 'terminal_at', 'run_id'])

def downgrade():
    op.drop_table('observability_turn')
    op.drop_table('observability_run_status')
    op.drop_table('observability_run_event')
