"""baseline slopanoc cases and knowledge schema

Revision ID: d2081e4fd455
Revises:
Create Date: 2026-09-07 14:22:29.673621

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2081e4fd455'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slopanoc_cases',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('external_reference', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('slopanoc_case_context_items',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_author', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_by_user_id', sa.String(), nullable=True),
    sa.Column('created_by_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('supporting_item_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['slopanoc_cases.case_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('slopanoc_case_memberships',
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['slopanoc_cases.case_id'], ),
    sa.PrimaryKeyConstraint('case_id', 'user_id')
    )
    op.create_table('slopanoc_case_session_links',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('session_user_id', sa.String(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=False),
    sa.Column('linked_by_user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['slopanoc_cases.case_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('slopanoc_knowledge_objects',
    sa.Column('knowledge_id', sa.String(), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('knowledge_id', 'version_label')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slopanoc_knowledge_objects')
    op.drop_table('slopanoc_case_session_links')
    op.drop_table('slopanoc_case_memberships')
    op.drop_table('slopanoc_case_context_items')
    op.drop_table('slopanoc_cases')
    # ### end Alembic commands ###
