// Synthetic safe DTOs for isolated tests only.
export const at='2026-10-08T12:00:00Z';
export const group={dimension:'gemini-2.5-flash',attempts:100,captured_attempts:100,quantity_known:95,quantity_partial:0,quantity_coverage:.95,quantities:Object.fromEntries(['input_tokens','output_tokens','candidate_tokens','cached_tokens','total_tokens','thought_tokens','tool_input_tokens','billable_characters'].map(q=>[q,{observed:null as number|null,known:0,unknown:100}]))};
export const usage={schema_version:1,environment:'development',start:at,end:at,group:'model',items:[group],next_cursor:null};
export const health={schema_version:1,environment:'development',state:'DEGRADED',pending:1,debt:1,conflicts:0,exhausted:0,admissions_failed:0,updated_at:at,last_observation:at,last_persistence:null,oldest_pending_at:at,oldest_debt_at:at,coverage_start:at,retention_months:24,retention_execution:'NOT_ACTIVATED'};
export const financialSource={source:'DETAILED_BILLING',state:'NOT_CONFIGURED',reason:'NOT_CONFIGURED',mode:'NOT_CONFIGURED',as_of:null,last_extraction:null,coverage_start:null,coverage_end:null,generation:null,row_count:0,unmapped_rows:0,price_evidence_rows:0,pending_partitions:0,policy:'PROVISIONAL',delayed_seconds:86400,stale_seconds:259200,cadence_seconds:3600};
export const billingSources={schema_version:1,environment:'development',sources:[financialSource,{...financialSource,source:'PRICING_EXPORT'},{...financialSource,source:'FOCUS'}]};
export const billingSummary={schema_version:1,environment:'development',period_basis:'usage',start:'2026-10-08',end:'2026-10-09',invoice_month:null,amount_basis:'ACTUAL_BILLED_COST',tax_basis:'SOURCE_TAX_SEPARATE',source:financialSource,coverage_complete:false,amounts:null as null|Array<Record<string,unknown>>,next_cursor:null};
export const pricingStatus={schema_version:1,environment:'development',amount_basis:'PRICING_EXPORT_CATALOG',source:{...financialSource,source:'PRICING_EXPORT'},earliest_pricing_as_of:null,latest_pricing_as_of:null,historical_policy:'NO_EXTRAPOLATION'};
export const billingAmount={currency:'EUR',category:'UNMAPPED',gross:'0.1',credits:'-0.02',adjustments:'0',tax:'0',rounding:'0',pre_credit:'0.1',net:'0.08',rows:1,unmapped_rows:1,mapping_coverage:'0',eur_net:'0.08',eur_state:'NATIVE_EUR'};
